os: Visual Studio 2015
init:
  - git config --global user.email "AppVeyor"
  - git config --global user.name "AppVeyor"
  - git config --global push.default simple
clone_depth: 10
build_script:
  - ps: |
      .\paket.bootstrapper.exe
      .\paket.exe restore
      .\lib\Copy-Libraries.ps1
      .\build.ps1
      if ($lastexitcode -ne 0){ exit $lastexitcode }
test: off
artifacts:
  - path: bin\*.nupkg