init:
  - git config --global user.email "AppVeyor"
  - git config --global user.name "AppVeyor"
  - git config --global push.default simple
  - choco install Paket.PowerShell
  - ps: (Get-Item Env:\PSModulePath).Value -Split ';'
clone_depth: 1
build_script:
  - ps: .\build.ps1
test: off
artifacts:
  - path: bin\*.nupkg