init:
  - git config --global user.email "AppVeyor"
  - git config --global user.name "AppVeyor"
  - git config --global push.default simple
  - choco install Paket.PowerShell -y
clone_depth: 1
build_script:
  - ps: >-
    $env:PSModulePath = "C:\ProgramData\chocolatey\lib\Paket.PowerShell\tools;$env:PSModulePath"

    .\build.ps1
test: off
artifacts:
  - path: bin\*.nupkg